source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

# ignore all warnings from all pods
inhibit_all_warnings!

def all_pods
    pod 'SDWebImage', '~>3.7.1'
    pod 'DACircularProgress'
    pod 'pop'
end


target "PhotoBrowserDemo" do
    all_pods
end
